spring:
  profiles:
    default: local
  jpa:
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  file:
    path: "/home/ec2-user/app/logs"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true