---
spring:
  config:
    activate:
      on-profile: real-db
  datasource:
    url: jdbc:mariadb://localhost:3306/hangilse-rds
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hsh8220@gmail.com
    password: jdiusivfbdbybeev
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  base64-secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNpa3NhdXJ1cy1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2lrc2F1cnVzCg==