INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ENGINEER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ACCOUNTING');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_MANAGER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_OWNER');
